### ISSUE TITLE
Light mode with dark taskbar/system?

### ISSUE THREAD

**Issue by ScribbleGhost** [EvanBurnette/ToggleDarkModeAHK#2]
Hi Evan,

Is there any way to make this AHK script able to toggle between "custom" and dark mode? That is, toggle between dark mode and light mode, where the taskbar is black (`SystemUsesLightTheme = 0`), but the app mode is light (`AppsUseLightTheme = 1`)?

I tried to change the light mode to:

```
RegWrite, REG_DWORD, HKEY_CURRENT_USER\Software\Microsoft\Windows\CurrentVersion\Themes\Personalize, SystemUsesLightTheme, 0
```

Note the `0` at the end instead pf `1` as in the original script.

But I can't get it to work for some reason. Any suggestions?

**Comment by EvanBurnette** [comment]
I would try to leave the script as is but add your customization at the bottom on separate lines.

**Comment by EvanBurnette** [comment]
Okay I think I found the problem. On line 8 we do `RegRead, light, HKEY_CURRENT_USER\Software\Microsoft\Windows\CurrentVersion\Themes\Personalize, SystemUsesLightTheme`

Change SystemUsesLightTheme to AppsUseLightTheme.

This line more reliably reads the state of your theme but it assumes you'd want to keep the system in sync with the apps. Since you only want to switch app colors, then you can delete all the system stuff and create a streamlined version of the script. If you create a solution you're happy with, if you want to make a pull request, I'll merge the app only version into the repo. Thanks for raising this issue! I will be personally switching to it!

**Comment by ScribbleGhost** [comment]
Thanks! Yeah, this works great for me. Glad to get rid of that nasty white taskbar 😂

```ahk
﻿#NoEnv  ; Recommended for performance and compatibility with future AutoHotkey releases.
; #Warn  ; Enable warnings to assist with detecting common errors.
SendMode Input  ; Recommended for new scripts due to its superior speed and reliability.
SetWorkingDir %A_ScriptDir%  ; Ensures a consistent starting directory.
; written with version 1.1.33.6

^#t::
RegRead, light, HKEY_CURRENT_USER\Software\Microsoft\Windows\CurrentVersion\Themes\Personalize, AppsUseLightTheme

if light ;make dark
{
    RegWrite, REG_DWORD, HKEY_CURRENT_USER\Software\Microsoft\Windows\CurrentVersion\Themes\Personalize, AppsUseLightTheme, 0
}
else ;make light
{
    RegWrite, REG_DWORD, HKEY_CURRENT_USER\Software\Microsoft\Windows\CurrentVersion\Themes\Personalize, AppsUseLightTheme, 1
}
return
```
